=== wdiide/wdiide/modules/schemas/public/page.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "from": {
      "type": "string",
      "minLength": 1
    },
    "checks": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "name",
          "condition"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "condition": {
            "type": "string"
          }
        }
      }
    },
    "rules": {
      "type": "array",
      "items": {
        "required": [],
        "properties": {}
      }
    },
    "fields": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "name",
          "label",
          "type",
          "size",
          "digits",
          "value",
          "format",
          "pattern",
          "isRequire"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "label": {
            "type": "string",
            "minLength": 1
          },
          "type": {
            "type": "string",
            "minLength": 1
          },
          "size": {
            "type": "number"
          },
          "digits": {
            "type": "number"
          },
          "value": {
            "type": "string",
            "minLength": 1
          },
          "format": {
            "type": "string",
            "minLength": 1
          },
          "pattern": {
            "type": "string"
          },
          "isRequire": {
            "type": "boolean"
          }
        }
      }
    }
  },
  "required": [
    "name",
    "from",
    "checks",
    "rules",
    "fields"
  ]
}

=== wdiide/wdiide/modules/schemas/src/schemas/page.json
{
  "name": "user",
  "from": "$project.models.produto",
  "checks": [
    {
      "name": "",
      "condition": ""
    }
  ],
  "rules": ["ALL", "CREATE", "READ", "UPDATE", "DELETE"],
  "fields": [
    {
      "name": "ID",
      "label": "Identificador",
      "type": "input",
      "size": 10,
      "digits": 6,
      "value": "10",
      "format": "text",
      "pattern": "",
      "isRequire": true
    }
  ]
}
